config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  namespace :api do
    namespace :v1 do
      get 'sakes' => 'sakes#index'
      get 'sakes/:id' => 'sakes#show'
      patch 'sakes/:id/like' => 'sakes#like'
      patch 'sakes/:id/dislike' => 'sakes#dislike'
      get 'sakes/:id/evaluation' => 'sakes#evaluation'
    end
  end

  namespace :developer do
    get 'sessions/new'
    delete 'sessions' => 'sessions#destroy'
  end

  namespace :admin do
    get 'sessions/new'
    post 'sessions' => 'sessions#create'
    delete 'sessions' => 'sessions#destroy'

    resources :sakes do
      collection do
        get 'tags'
      end
    end
  end

  scope module: :developer do
    [:twitter].each do |provider|
      get "auth/#{provider}/callback" => "omniauth_callbacks##{provider}"
    end
  end

  root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sake.rb
class Sake < ApplicationRecord
  acts_as_taggable

  validates :name, presence: true
  validates :yomi, presence: true

  def like(user)
    # 30分以内の評価は同一のものとみなす
    se = SakeEvaluation.where(sake_id: self.id, user_id: user.id, updated_at: (Time.now-30.minutes)..Time.now).order('id desc')
    if se.present?
      se.first.increment!(:evaluation)
    else
      SakeEvaluation.create!(sake_id: self.id, user_id: user.id, evaluation: 1)
    end
  end

  def dislike(user)
    # 30分以内の評価は同一のものとみなす
    se = SakeEvaluation.where(sake_id: self.id, user_id: user.id, updated_at: (Time.now-30.minutes)..Time.now).order('id desc')
    if se.present?
      se.first.decrement!(:evaluation)
    else
      SakeEvaluation.create!(sake_id: self.id, user_id: user.id, evaluation: -1)
    end
  end
end

app/models/sake_evaluation.rb
class SakeEvaluation < ApplicationRecord
end

app/models/social_profile.rb
class SocialProfile < ApplicationRecord
  belongs_to :user

  def self.find_or_initialize_for_oauth(auth)
    profile = find_or_initialize_by(uid: auth["uid"], provider: auth["provider"]) do |pf|
      pf.name = auth["info"]["name"]
      pf.nickname = auth["info"]["nickname"]
      pf.image_url = auth["info"]["image"]
    end
    profile
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin/sakes_controller.rb
class Admin::SakesController < ApplicationController
  include Monban::ControllerHelpers
  layout 'doorkeeper/admin'

  def index
    @sakes = Sake.all.page(params[:page]).per(50)
  end

  def new
    @sake = Sake.new
  end

  def create
    sake = Sake.new(sake_params)
    sake.tag_list = params[:sake][:tag_list]
    if sake.save
      flash[:success] = "作成しました。"
      redirect_to edit_admin_sake_path(sake.id) and return
    else
      flash[:error] = "作成に失敗しました。"
    end

    redirect_to new_admin_sake_path
  end

  def edit
    @sake = Sake.find(params[:id])
  end

  def update
    sake = Sake.find(params[:id])

    if sake.update_attributes(sake_params)
      flash[:success] = "変更しました。"
    else
      flash[:error] = "変更に失敗しました。"
    end

    redirect_to edit_admin_sake_path(sake.id)
  end

  def tags
    render json: ActsAsTaggableOn::Tag.all.pluck(:name)
  end

  private
  def sake_params
    params.require(:sake).permit(:name, :yomi, :kuramoto, :locality, :raw_rice, :cleaning_rate,
      :nihonsyu_degree, :amino_degree, :alcohol_content, :acidit, :use_yeast, :tag_list)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  include Monban::ControllerHelpers

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && authenticate(user, params[:session][:password])
      sign_in(user)
      redirect_to oauth_applications_path
    else
      redirect_to admin_sessions_new_path
    end
  end

  def destroy
    sign_out

    redirect_to admin_sessions_new_path
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :doorkeeper_authorize!

  respond_to :json

  private
  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/v1/sakes_controller.rb
class Api::V1::SakesController < Api::ApplicationController
  def index
    if params[:keyword].blank?
      sakes = Sake.all
    else
      sakes = Sake.where('name like :keyword or yomi like :keyword_kata',
                {keyword: "%#{params[:keyword]}%", keyword_kata: "%#{Moji.hira_to_kata(params[:keyword])}%"})
    end

    sakes = paginate sakes.order(:id), page: params[:page], per_page: params[:per_page] || 20

    render json: sakes.map{|sake| Resources::V1::Sake.new(sake).as_json(only: [:id, :name, :yomi])}
  end

  def show
    render json: Resources::V1::Sake.new(Sake.find(params[:id]))
  end

  def like
    Sake.find(params[:id]).like(current_resource_owner)

    head :no_content
  end

  def dislike
    Sake.find(params[:id]).dislike(current_resource_owner)

    head :no_content
  end

  def evaluation
    se = SakeEvaluation.where(sake_id: params[:id], user_id: current_resource_owner.id, updated_at: (Time.now-30.minutes)..Time.now).first
    render json: {evaluation: se.present? ? se.evaluation : 0}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developer/omniauth_callbacks_controller.rb
class Developer::OmniauthCallbacksController < ApplicationController
  include Monban::ControllerHelpers

  def twitter
    profile = SocialProfile.find_or_initialize_for_oauth(request.env['omniauth.auth'])
    user = profile.user

    unless user
      user = User.new(
        username: request.env['omniauth.auth']["info"]["name"]
      )
      user.save(validate: false)
      profile.user = user
      profile.save
    end

    sign_in(user)

    if session[:return_to]
      redirect_to session[:return_to]
      session[:return_to] = nil
    else
      redirect_to oauth_applications_path
    end
  end
end

app/controllers/developer/sessions_controller.rb
class Developer::SessionsController < ApplicationController
  include Monban::ControllerHelpers

  def new
  end

  def destroy
    sign_out

    redirect_to developer_sessions_new_path
  end
end

app/controllers/doorkeeper_custom_application_controller.rb
class DoorkeeperCustomApplicationController < ApplicationController
  include Monban::ControllerHelpers
end

app/helpers/admin/sakes_helper.rb
module Admin::SakesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developer/sessions_helper.rb
module Developer::SessionsHelper
end

app/views/admin/sakes/_form.html.erb
<table class="table table-striped">
  <tbody>
    <tr>
      <td>お酒名</td>
      <td><%= f.text_field :name, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>読み</td>
      <td><%= f.text_field :yomi, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>カテゴリ</td>
      <td><%= f.text_field :tag_list, {class: 'form-control', data: {role: 'tagsinput'}, value: @sake.tag_list.join(',')} %></td>
    </tr>
    <tr>
      <td>蔵元</td>
      <td><%= f.text_field :kuramoto, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>都道府県</td>
      <td><%= f.text_field :locality, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>原料米</td>
      <td><%= f.text_field :raw_rice, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>精米度</td>
      <td><%= f.text_field :cleaning_rate, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>日本酒度</td>
      <td><%= f.text_field :nihonsyu_degree, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>アミノ酸度</td>
      <td><%= f.text_field :amino_degree, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>アルコール度</td>
      <td><%= f.text_field :alcohol_content, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>酸度</td>
      <td><%= f.text_field :acidit, class: 'form-control' %></td>
    </tr>
    <tr>
      <td>使用酵母</td>
      <td><%= f.text_field :use_yeast, class: 'form-control' %></td>
    </tr>
  </tbody>
</table>

<script>
  var tags = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    prefetch: {
      url: "<%= tags_admin_sakes_url %>",
      filter: function(list) {
        return list;
      }
    }
  });
  tags.initialize();

  $('#sake_tag_list').tagsinput({
    typeaheadjs: {
      name: 'tags',
      source: tags.ttAdapter()
    },
    freeInput: true
  });
</script>

app/views/admin/sakes/edit.html.erb
<%= form_for @sake, url: admin_sake_path(@sake.id), method: :put do |f| %>
  <%= render partial: 'form', locals: {f: f} %>

  <%= f.submit '更新', class: 'btn btn-default' %>
<% end %>

app/views/admin/sakes/index.html.erb
<%= link_to '新規作成', new_admin_sake_path, class: 'btn btn-success' %>
<table class="table table-striped">
  <thead>
    <th>お酒名</th>
    <th>読み</th>
    <th>蔵元</th>
    <th>都道府県</th>
    <th>原料米</th>
    <th>精米度</th>
    <th>日本酒度</th>
    <th>アミノ酸度</th>
    <th>アルコール度</th>
    <th>酸度</th>
    <th>使用酵母</th>
  </thead>
  <tbody>
    <% @sakes.each do |sake| %>
      <tr>
        <td><%= link_to sake.name, edit_admin_sake_path(sake.id) %></td>
        <td><%= sake.yomi %></td>
        <td><%= sake.kuramoto %></td>
        <td><%= sake.locality %></td>
        <td><%= sake.raw_rice %></td>
        <td><%= sake.cleaning_rate %></td>
        <td><%= sake.nihonsyu_degree %></td>
        <td><%= sake.amino_degree %></td>
        <td><%= sake.alcohol_content %></td>
        <td><%= sake.acidit %></td>
        <td><%= sake.use_yeast %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @sakes %>

app/views/admin/sakes/new.html.erb
<%= form_for @sake, url: admin_sakes_path do |f| %>
  <%= render partial: 'form', locals: {f: f} %>

  <%= f.submit '作成', class: 'btn btn-default' %>
<% end %>

app/views/doorkeeper/applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_application_path(application) do %>
  <input type="hidden" name="_method" value="delete">
  <%= submit_tag t('doorkeeper.applications.buttons.destroy'), onclick: "return confirm('#{ t('doorkeeper.applications.confirmations.destroy') }')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/applications/_form.html.erb
<%= form_for application, url: doorkeeper_submit_path(application), html: {class: 'form-horizontal', role: 'form'} do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger" data-alert><p><%= t('doorkeeper.applications.form.error') %></p></div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:name].present?}" do %>
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :name %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:redirect_uri].present?}" do %>
    <%= f.label :redirect_uri, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :redirect_uri, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :redirect_uri %>
      <span class="help-block">
        <%= t('doorkeeper.applications.help.redirect_uri') %>
      </span>
      <% if Doorkeeper.configuration.native_redirect_uri %>
          <span class="help-block">
            <%= raw t('doorkeeper.applications.help.native_redirect_uri', native_redirect_uri: "<code>#{ Doorkeeper.configuration.native_redirect_uri }</code>") %>
          </span>
      <% end %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:scopes].present?}" do %>
    <%= f.label :scopes, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :scopes, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :scopes %>
      <span class="help-block">
        <%= t('doorkeeper.applications.help.scopes') %>
      </span>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t('doorkeeper.applications.buttons.submit'), class: "btn btn-primary" %>
      <%= link_to t('doorkeeper.applications.buttons.cancel'), oauth_applications_path, :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/doorkeeper/applications/edit.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/index.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<p><%= link_to t('.new'), new_oauth_application_path, class: 'btn btn-success' %></p>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.callback_url') %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @applications.each do |application| %>
    <tr id="application_<%= application.id %>">
      <td><%= link_to application.name, oauth_application_path(application) %></td>
      <td><%= application.redirect_uri %></td>
      <td><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(application), class: 'btn btn-link' %></td>
      <td><%= render 'delete_form', application: application %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/doorkeeper/applications/new.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/show.html.erb
<div class="page-header">
  <h1><%= t('.title', name: @application.name) %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <h4><%= t('.application_id') %>:</h4>
    <p><code id="application_id"><%= @application.uid %></code></p>

    <h4><%= t('.secret') %>:</h4>
    <p><code id="secret"><%= @application.secret %></code></p>

    <h4><%= t('.scopes') %>:</h4>
    <p><code id="scopes"><%= @application.scopes %></code></p>

    <h4><%= t('.callback_urls') %>:</h4>

    <table>
      <% @application.redirect_uri.split.each do |uri| %>
        <tr>
          <td>
            <code><%= uri %></code>
          </td>
          <td>
            <%= link_to t('doorkeeper.applications.buttons.authorize'), oauth_authorization_path(client_id: @application.uid, redirect_uri: uri, response_type: 'code', scope: @application.scopes), class: 'btn btn-success', target: '_blank' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-4">
    <h3><%= t('.actions') %></h3>

    <p><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(@application), class: 'btn btn-primary' %></p>

    <p><%= render 'delete_form', application: @application, submit_btn_css: 'btn btn-danger' %></p>
  </div>
</div>

app/views/doorkeeper/authorizations/error.html.erb
<div class="page-header">
  <h1><%= t('doorkeeper.authorizations.error.title') %></h1>
</div>

<main role="main">
  <pre><%= @pre_auth.error_response.body[:error_description] %></pre>
</main>

app/views/doorkeeper/authorizations/new.html.erb
<header class="page-header" role="banner">
  <h1><%= t('.title') %></h1>
</header>

<main role="main">
  <p class="h4">
    <%= raw t('.prompt', client_name: "<strong class=\"text-info\">#{ @pre_auth.client.name }</strong>") %>
  </p>

  <% if @pre_auth.scopes.count > 0 %>
    <div id="oauth-permissions">
      <p><%= t('.able_to') %>:</p>

      <ul class="text-info">
        <% @pre_auth.scopes.each do |scope| %>
          <li><%= t scope, scope: [:doorkeeper, :scopes] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_tag oauth_authorization_path, method: :post do %>
      <%= hidden_field_tag :client_id, @pre_auth.client.uid %>
      <%= hidden_field_tag :redirect_uri, @pre_auth.redirect_uri %>
      <%= hidden_field_tag :state, @pre_auth.state %>
      <%= hidden_field_tag :response_type, @pre_auth.response_type %>
      <%= hidden_field_tag :scope, @pre_auth.scope %>
      <%= submit_tag t('doorkeeper.authorizations.buttons.authorize'), class: "btn btn-success btn-lg btn-block" %>
    <% end %>
    <%= form_tag oauth_authorization_path, method: :delete do %>
      <%= hidden_field_tag :client_id, @pre_auth.client.uid %>
      <%= hidden_field_tag :redirect_uri, @pre_auth.redirect_uri %>
      <%= hidden_field_tag :state, @pre_auth.state %>
      <%= hidden_field_tag :response_type, @pre_auth.response_type %>
      <%= hidden_field_tag :scope, @pre_auth.scope %>
      <%= submit_tag t('doorkeeper.authorizations.buttons.deny'), class: "btn btn-danger btn-lg btn-block" %>
    <% end %>
  </div>
</main>

app/views/doorkeeper/authorizations/show.html.erb
<header class="page-header">
  <h1><%= t('.title') %>:</h1>
</header>

<main role="main">
  <code id="authorization_code"><%= params[:code] %></code>
</main>

app/views/doorkeeper/authorized_applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_authorized_application_path(application) do %>
  <input type="hidden" name="_method" value="delete">
  <%= submit_tag t('doorkeeper.authorized_applications.buttons.revoke'), onclick: "return confirm('#{ t('doorkeeper.authorized_applications.confirmations.revoke') }')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/authorized_applications/index.html.erb
<header class="page-header">
  <h1><%= t('doorkeeper.authorized_applications.index.title') %></h1>
</header>

<main role="main">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= t('doorkeeper.authorized_applications.index.application') %></th>
      <th><%= t('doorkeeper.authorized_applications.index.created_at') %></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.name %></td>
        <td><%= application.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format')) %></td>
        <td><%= render 'delete_form', application: application %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/doorkeeper/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Doorkeeper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t('doorkeeper.layouts.admin.nav.oauth2_provider'), oauth_applications_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <%= content_tag :li, class: "#{'active' if request.path == oauth_applications_path}" do %>
        <%= link_to t('doorkeeper.layouts.admin.nav.applications'), oauth_applications_path %>
      <% end %>
      <%= content_tag :li do %>
        <%= link_to t('doorkeeper.layouts.admin.nav.home'), root_path %>
      <% end %>
      <% if signed_in? %>
        <%= content_tag :li do %>
          <%= link_to "Sign out", admin_sessions_path, method: :delete %>
        <% end %>
      <% end %>
      <%= content_tag :li do %>
        <%= link_to "お酒管理", admin_sakes_path %>
      <% end %>
    </ul>
  </div>
</div>
<div class="container">
  <%- if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end -%>
  <%- if flash[:success].present? %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end -%>
  <%- if flash[:error].present? %>
    <div class="alert alert-danger">
      <%= flash[:error] %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>

app/views/layouts/doorkeeper/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('doorkeeper.layouts.application.title') %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag "doorkeeper/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <%- if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>